### ISSUE TITLE
MaxHash doesn't validate inputs properly

### ISSUE THREAD

**Issue by itaygr** [maxeler/maxpower#70]
Example:

FMemBacking means storage width of 64 bits. If an entry exceeds that due to key validation, it'll fail in the following way:
 Number must be positive

```java
Exception Stack Trace com.maxeler.utils.MaxUtilException: 
   at com.maxeler.utils.MaxDCMath.nextPowerOfTwo(MaxDCMath.java:216)
   at com.maxeler.maxcompiler.v2.utils.MathUtils.nextPowerOfTwo(MathUtils.java:111)
   at maxpower.hash.mem.BurstMemBacking.getNumEntriesPerBurst(BurstMemBacking.maxj:31)
   at maxpower.hash.mem.BurstMemBacking.getNumOccupiedBurstsPerTable(BurstMemBacking.maxj:45)
   at maxpower.hash.mem.BurstMemBacking.getNumOccupiedBursts(BurstMemBacking.maxj:52)
   at maxpower.hash.mem.FMemBacking.getNumOccupiedBursts(FMemBacking.maxj:1)
   at maxpower.hash.mem.FMemBacking.<init>(FMemBacking.maxj:24)
   at maxpower.hash.mem.MemBacking.create(MemBacking.maxj:41)
   at maxpower.hash.MinimalPerfectHashMap.<init>(MinimalPerfectHashMap.maxj:79)
   at maxpower.hash.MaxHashFactory.create(MaxHashFactory.maxj:51)
```

**Comment by mbazley** [comment]
Fixed by #73 - should be closed.
